spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mxrtcansaglam/turkcell-crm-config-server-main.git
server:
  port: 8050

