eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 9002
spring:
  application:
    name: gatewayservice
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true




